export const daisyuiTheme = {
  'base-100': 'var(--color-background)',
  'base-200': 'var(--color-surface)',
  'base-300': 'var(--color-surface-container-low)',
  'base-content': 'var(--color-on-background)',
  primary: 'var(--color-primary)',
  'primary-content': 'var(--color-on-primary)',
  secondary: 'var(--color-secondary)',
  'secondary-content': 'var(--color-on-secondary)',
  accent: 'var(--color-accent)',
  'accent-content': 'var(--color-on-accent)',
  neutral: 'var(--color-neutral)',
  'neutral-content': 'var(--color-on-neutral)',
  info: 'var(--color-info)',
  'info-content': 'var(--color-on-info)',
  success: 'var(--color-success)',
  'success-content': 'var(--color-on-success)',
  warning: 'var(--color-warning)',
  'warning-content': 'var(--color-on-warning)',
  error: 'var(--color-error)',
  'error-content': 'var(--color-on-error)',
};
